TeamSpeak: 'ts.deltapvp.com'
MySQL:
  Enabled: false
  IP: 'deltaclanofficial.ml'
  Name: 'deltamc'
  Username: 'root'
  Password: 'password'
Strings:
  Blacklisted_Reason: "&7You are &cblacklisted &7from Delta &cpermanently&7! \\n&f\\n&7Reason: &c%reason%\\n&7Staff: &c%staff%\\n&f\\n&7Appeal at &b&ndeltapvp.net&7!"
